/**
 * Pre-baked Integration Discovery Reports for the 3 Emergent projects.
 * Generated by AfinityOS discovery engine against:
 *   - https://crm-automation-ref.preview.emergentagent.com
 *   - https://point-vault.preview.emergentagent.com
 *   - https://insurtech-ui-upgrade.preview.emergentagent.com
 */
export const PREBAKED_REPORTS = [
  {
    id: 'crm-automation-ref',
    label: 'CRM Automation Ref — powers Sales/Marketing/Support',
    baseUrl: 'https://crm-automation-ref.preview.emergentagent.com',
    framework: 'FastAPI (Python)',
    productName: 'SalesHub Platform API',
    productVersion: '2.0.0',
    features: ['Multi-tenant', 'RBAC', 'CRM', 'Sales', 'Support'],
    authMechanism: 'Bearer JWT',
    hasOpenApi: false,
    docsExposed: false,
    docsNote: 'OpenAPI /docs endpoint is disabled in this deployment. Endpoints discovered via runtime sampling.',
    discoveredEndpoints: [
      { method: 'GET',  path: '/api/',                  authRequired: false, purpose: 'API root — returns service identity' },
      { method: 'POST', path: '/api/auth/login',        authRequired: false, purpose: 'Obtain JWT (email + password)' },
      { method: 'POST', path: '/api/auth/register',     authRequired: false, purpose: 'Register a new user' },
      { method: 'GET',  path: '/api/roles',             authRequired: false, purpose: 'Public list of RBAC roles' },
      { method: 'GET',  path: '/api/users',             authRequired: true,  purpose: 'List tenant users' },
      { method: 'GET',  path: '/api/organizations',     authRequired: true,  purpose: 'List organizations (tenants)' },
      { method: 'GET',  path: '/api/contacts',          authRequired: true,  purpose: 'CRM contacts' },
      { method: 'GET',  path: '/api/customers',        authRequired: true,  purpose: 'CRM customer accounts' },
      { method: 'GET',  path: '/api/leads',             authRequired: true,  purpose: 'Sales leads' },
      { method: 'GET',  path: '/api/deals',             authRequired: true,  purpose: 'Sales deals / opportunities' },
      { method: 'GET',  path: '/api/activities',        authRequired: true,  purpose: 'Sales activities log' },
      { method: 'GET',  path: '/api/tasks',             authRequired: true,  purpose: 'Sales tasks queue' },
      { method: 'GET',  path: '/api/notifications',     authRequired: true,  purpose: 'User notifications' },
    ],
    connectorMapping: {
      sales: { configurable: true, baseUrl: 'https://crm-automation-ref.preview.emergentagent.com', authStrategy: 'login+jwt' },
      marketing: { configurable: true, baseUrl: 'https://crm-automation-ref.preview.emergentagent.com', authStrategy: 'login+jwt' },
      support: { configurable: true, baseUrl: 'https://crm-automation-ref.preview.emergentagent.com', authStrategy: 'login+jwt' },
    },
    notes: [
      'Auth is JWT obtained via POST /api/auth/login. AfinityOS connectors will login as a service account, cache the access token, and inject it as `Authorization: Bearer <token>` on every call.',
      'Some routes (campaigns, tickets, knowledge-base) were not discoverable from outside because the OpenAPI spec is disabled in the deployment. Once we have credentials we can list them dynamically via /api/me + role-scoped endpoints.',
    ],
  },
  {
    id: 'point-vault',
    label: 'Point Vault — powers Rewards',
    baseUrl: 'https://point-vault.preview.emergentagent.com',
    framework: 'FastAPI (Python)',
    productName: 'RewardsHub API',
    productVersion: '1.0.0',
    features: ['Loyalty', 'Points', 'Redemptions'],
    authMechanism: 'Bearer JWT',
    hasOpenApi: false,
    docsExposed: false,
    discoveredEndpoints: [
      { method: 'GET',  path: '/api/',                  authRequired: false, purpose: 'API root — "RewardsHub API is running"' },
      { method: 'GET',  path: '/api/health',            authRequired: false, purpose: 'Health check' },
      { method: 'POST', path: '/api/auth/login',        authRequired: false, purpose: 'Obtain JWT' },
      { method: 'POST', path: '/api/auth/register',     authRequired: false, purpose: 'Register user' },
      { method: 'GET',  path: '/api/rewards',           authRequired: false, purpose: 'Public reward catalog (returned real items including "RM5 Cash Rebate" etc.)' },
      { method: 'GET',  path: '/api/redemptions',       authRequired: true,  purpose: 'User redemption history' },
    ],
    connectorMapping: {
      rewards: { configurable: true, baseUrl: 'https://point-vault.preview.emergentagent.com', authStrategy: 'login+jwt' },
    },
    notes: [
      'GET /api/rewards is PUBLIC and returns a live catalog. AfinityOS already proved it can read this in mock mode — LIVE will pull the real list.',
      'Award/redeem endpoints require auth; AfinityOS connector will perform login+jwt against a service account.',
    ],
  },
  {
    id: 'insurtech-ui-upgrade',
    label: 'Insurance Platform',
    baseUrl: 'https://insurtech-ui-upgrade.preview.emergentagent.com',
    framework: 'Go HTTP (default mux — frontend host)',
    productName: 'Unknown',
    productVersion: 'Unknown',
    features: ['UI only at this host'],
    authMechanism: 'Unknown (no backend reachable)',
    hasOpenApi: false,
    docsExposed: false,
    discoveredEndpoints: [],
    connectorMapping: {
      insurance: { configurable: false, baseUrl: null, authStrategy: 'unknown', status: 'no-backend-discovered' },
    },
    notes: [
      'The host responds with the Emergent SPA loader for navigational paths and a Go-style "404 page not found" for /api/* — i.e. there is no backend mounted at this URL.',
      'Likely setup: this is the frontend (insurtech-ui-upgrade) and the actual insurance backend is a sibling Emergent project. Possible candidates were probed (insurtech-api, insurance-api, insurtech-backend) — none resolved.',
      'ACTION: please share the insurance BACKEND URL (or the sibling project name) so the Insurance Connector can be flipped LIVE. Until then the Insurance Connector stays in MOCK mode with realistic responses.',
    ],
  },
];
